project_id = "vsruezynaanqprobpvrr"

[functions.ai-chat]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.verify-stripe-account]
verify_jwt = true

[functions.verify-rent-payment]
verify_jwt = false

[functions.create-rent-payment]
verify_jwt = true

[functions.release-escrow]
verify_jwt = true

[functions.auto-release-escrow]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.sign-rental-agreement]
verify_jwt = true
