project_id = "vsruezynaanqprobpvrr"

[functions.ai-chat]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.verify-stripe-account]
verify_jwt = true