import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'FR' | 'EN' | 'AR';

interface LanguageContextType {
  currentLang: Language;
  setCurrentLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  FR: {
    // Navigation
    buy: 'Acheter',
    rent: 'Louer',
    shortStay: 'Short Stay',
    about: 'À propos',
    login: 'Se connecter',
    publishProperty: 'Publier une annonce',
    
    // Hero
    heroTitle: 'Holibayt',
    heroSubtitle: 'Achetez. Louez. Vivez l\'Algérie autrement.',
    heroDescription: 'La première plateforme immobilière digitale nouvelle génération pour l\'Algérie.',
    
    // Quick Access
    buyProperty: 'Acheter un bien',
    rentProperty: 'Louer un logement',
    shortStayProperty: 'Court séjour',
    start: 'Commencer',
    bookNow: 'Réserver maintenant',
    
    // Property
    bedrooms: 'Chambres',
    bathrooms: 'Salles de bain',
    area: 'Surface',
    
    // Common
    search: 'Rechercher',
    cancel: 'Annuler',
    save: 'Enregistrer',
    clear: 'Effacer',
    from: 'Du',
    to: 'Au',
    selectDate: 'Sélectionner une date',
    selectDates: 'Sélectionner des dates',
    
    // Login
    loginSuccess: 'Connexion réussie!',
    loginSuccessDesc: 'Vous êtes maintenant connecté à votre compte Holibayt.',
    loginDescription: 'Connectez-vous à votre compte Holibayt',
    email: 'Adresse email',
    emailPlaceholder: 'votre@email.com',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié?',
    noAccount: 'Vous n\'avez pas de compte?',
    createAccount: 'Créer un compte',
    
    // Pages
    propertiesForSale: 'Propriétés à Vendre',
    propertiesForSaleDesc: 'Découvrez nos meilleures propriétés disponibles à l\'achat',
    propertiesForRent: 'Propriétés à Louer',
    propertiesForRentDesc: 'Trouvez votre location idéale',
    shortStayTitle: 'Séjours Courts',
    shortStayDesc: 'Hébergements parfaits pour vos courts séjours',
    
    // Quick Access Section
    howCanWeHelp: 'Comment pouvons-nous vous aider ?',
    quickEntriesDesc: 'Des entrées rapides pour tous vos besoins immobiliers',
    buyPropertyTitle: 'Acheter un bien',
    buyPropertyDesc: 'Découvrez les meilleures opportunités à la vente',
    buyPropertySubtitle: 'Investissement & résidence principale',
    rentPropertyTitle: 'Louer un logement',
    rentPropertyDesc: 'Trouvez votre prochain chez-vous',
    rentPropertySubtitle: 'Location longue durée',
    shortStayTitle2: 'Court séjour',
    shortStayDesc2: 'Réservez votre hébergement pour quelques nuits',
    shortStaySubtitle: 'Vacances & voyages d\'affaires',
    needHelp: 'Besoin d\'aide pour faire votre choix ?',
    speakToAdvisor: 'Parler à un conseiller',
    
    // Services Section
    threeWaysToLive: 'Trois façons de',
    liveAlgeria: 'vivre l\'Algérie',
    platformDesc: 'Une plateforme unique pour tous vos besoins immobiliers. Que vous cherchiez à acheter, louer ou séjourner, nous vous accompagnons avec confiance et transparence.',
    buyTitle: 'Acheter',
    buySubtitle: 'Trouvez votre futur chez-vous',
    buyDescription: 'Découvrez une sélection rigoureuse de biens immobiliers vérifiés. De l\'appartement en centre-ville à la villa en bord de mer, trouvez le bien de vos rêves en Algérie.',
    rentTitle: 'Louer',
    rentSubtitle: 'Location longue durée',
    rentDescription: 'Que vous soyez étudiant, professionnel ou famille, trouvez votre location idéale avec des garanties de sécurité et des propriétaires de confiance.',
    stayTitle: 'Short Stay',
    staySubtitle: 'Séjours courts et vacances',
    stayDescription: 'L\'Airbnb algérien ! Réservez votre séjour parfait pour vos vacances, voyages d\'affaires ou visites familiales. Logements uniques et expériences authentiques.',
    explore: 'Explorer',
    whyChooseHolibayt: 'Pourquoi choisir Holibayt ?',
    securityGuaranteed: 'Sécurité garantie',
    securityDesc: 'Tous nos biens et utilisateurs sont vérifiés',
    premiumQuality: 'Qualité premium',
    qualityDesc: 'Une sélection rigoureuse pour votre satisfaction',
    support247: 'Support 24/7',
    supportDesc: 'Une équipe dédiée à votre service',
    
    // Hero placeholders and options
    cityNeighborhood: 'Ville, quartier ou adresse',
    whereToRent: 'Où cherchez-vous à louer ?',
    stayDestination: 'Destination de votre séjour',
    propertyType: 'Type de bien',
    apartment: 'Appartement',
    house: 'Maison',
    villa: 'Villa',
    land: 'Terrain',
    maxBudget: 'Budget max',
    housingType: 'Type de logement',
    studio: 'Studio',
    room: 'Chambre',
    maxRentMonth: 'Loyer max/mois',
    stayDates: 'Dates de séjour',
    stayDuration: 'Durée du séjour',
    night: 'nuit',
    nights: 'nuits',
    quickSelection: 'Sélection rapide',
    oneNight: '1 nuit',
    oneWeek: '1 semaine',
    weekend: 'Week-end',
    oneMonth: '1 mois',
    checkIn: 'Arrivée',
    checkOut: 'Départ',
    travelers: 'Voyageurs',
    availableProperties: 'Biens disponibles',
    satisfiedUsers: 'Utilisateurs satisfaits',
    wilayasCovered: 'Wilayas couvertes',
    
    // Footer translations
    footerDescription: 'Votre plateforme immobilière de confiance en Algérie',
    quickLinks: 'Liens rapides',
    services: 'Services',
    contact: 'Contact',
    propertyValuation: 'Évaluation immobilière',
    legalSupport: 'Support juridique',
    mortgageAdvice: 'Conseils hypothécaires',
    allRightsReserved: 'Tous droits réservés',
    
    // About page translations
    aboutBeitik: 'À propos de Beitik',
    aboutDescription: 'Beitik est la plateforme immobilière de référence en Algérie, connectant acheteurs, vendeurs et locataires depuis plus de 15 ans. Notre mission est de simplifier vos transactions immobilières.',
    properties: 'Propriétés',
    propertiesListed: 'Propriétés listées',
    clients: 'Clients',
    satisfiedClients: 'Clients satisfaits',
    experience: 'Expérience',
    years: 'ans',
    realEstateExpertise: 'D\'expertise immobilière',
    security: 'Sécurité',
    secureTransactions: 'Transactions sécurisées',
    ourStory: 'Notre Histoire',
    storyParagraph1: 'Fondée en 2009, Beitik a révolutionné le marché immobilier algérien en créant la première plateforme en ligne dédiée à l\'immobilier en Algérie.',
    storyParagraph2: 'Nous avons commencé avec une vision simple : rendre l\'immobilier accessible à tous et faciliter les transactions entre particuliers et professionnels.',
    storyParagraph3: 'Aujourd\'hui, nous sommes fiers d\'être la plateforme de référence avec plus de 10,000 propriétés actives et une communauté de plus de 50,000 utilisateurs.',
    storyParagraph4: 'Notre équipe d\'experts travaille chaque jour pour améliorer votre expérience et vous accompagner dans vos projets immobiliers.',
    ourMission: 'Notre Mission',
    missionDescription: 'Démocratiser l\'accès à l\'immobilier en Algérie en offrant une plateforme moderne, sécurisée et facile à utiliser.',
    ourVision: 'Notre Vision',
    visionDescription: 'Devenir la référence incontournable de l\'immobilier au Maghreb et transformer la façon dont les gens achètent et louent.',
    ourValues: 'Nos Valeurs',
    valuesDescription: 'Transparence, confiance, innovation et service client d\'exception sont au cœur de tout ce que nous faisons.',
    
    // Publish property translations
    addPropertyDetails: 'Ajoutez les détails de votre propriété',
    propertyPublished: 'Propriété publiée!',
    propertySubmittedSuccess: 'Votre propriété a été soumise avec succès et sera examinée sous peu.',
    
    // Cities and additional translations
    followUs: 'Suivez-nous',
    privacyPolicy: 'Politique de confidentialité',
    termsOfUse: 'Conditions d\'utilisation',
    cookies: 'Cookies',
    
    // Contact advisor translations
    chooseContactMethod: 'Choisissez votre méthode de contact préférée',
    multipleWaysConnect: 'Plusieurs façons de vous connecter avec nos conseillers experts',
    phoneSupport: 'Support téléphonique',
    speakDirectly: 'Parlez directement avec nos conseillers',
    emailSupport: 'Support par email',
    getDetailedAssistance: 'Obtenez une assistance détaillée par email',
    liveChat: 'Chat en direct',
    instantMessaging: 'Messagerie instantanée avec notre équipe',
    chatNow: 'Chatter maintenant',
    available247: 'Disponible 24/7',
    responseWithin2h: 'Réponse sous 2 heures',
    onlineNow: 'En ligne maintenant',
    expertAdvisors: 'Conseillers experts',
    averageRating: 'Note moyenne',
    averageResponseTime: 'Temps de réponse moyen',
    sendMessage: 'Envoyer un message',
    fullName: 'Nom complet',
    yourFullName: 'Votre nom complet',
    phoneNumber: 'Numéro de téléphone',
    subject: 'Sujet',
    whatCanWeHelp: 'Comment pouvons-nous vous aider?',
    message: 'Message',
    tellUsMore: 'Parlez-nous de vos besoins immobiliers...',
    ourOffice: 'Notre bureau',
    businessHours: 'Heures d\'ouverture',
    mondayFriday: 'Lundi - Vendredi: 8h00 - 20h00',
    saturday: 'Samedi: 9h00 - 18h00',
    sunday: 'Dimanche: 10h00 - 16h00',
    needImmediateHelp: 'Besoin d\'aide immédiate?',
    call247Hotline: 'Appelez notre ligne d\'urgence 24/7',
    
    // Property and publish property translations
    propertyTypeTranslation: 'Type de Propriété',
    forSale: 'À Vendre', 
    forRent: 'À Louer',
    shortStayRent: 'Court Séjour',
    basicInformation: 'Informations de Base',
    propertyTitleField: 'Titre de la Propriété',
    propertyTitlePlaceholder: 'Ex: Belle villa avec jardin',
    categoryField: 'Catégorie',
    selectCategory: 'Sélectionner la catégorie',
    duplex: 'Duplex',
    hotel: 'Hôtel',
    guesthouse: 'Maison d\'hôtes',
    locationField: 'Localisation',
    cityField: 'Ville',
    district: 'Quartier/Zone',
    fullAddress: 'Adresse Complète',
    propertyDetailsTitle: 'Détails de la Propriété',
    chambers: 'Chambres',
    numberField: 'Nombre',
    areaField: 'Surface (m²)',
    floorField: 'Étage',
    floorExample: 'Ex: 2ème',
    pricing: 'Prix',
    priceDZD: 'Prix (DZD)',
    priceExample: 'Ex: 2,500,000',
    priceTypeField: 'Type de Prix',
    totalPrice: 'Prix total',
    monthlyPrice: 'Par mois',
    dailyPrice: 'Par jour',
    weeklyPrice: 'Par semaine',
    featuresAmenities: 'Caractéristiques et Équipements',
    parkingFeature: 'Parking',
    swimmingPoolFeature: 'Piscine',
    gardenFeature: 'Jardin',
    balconyFeature: 'Balcon',
    elevatorFeature: 'Ascenseur',
    securityFeature: 'Sécurité',
    furnishedFeature: 'Meublé',
    airConditioningFeature: 'Climatisation',
    gymFeature: 'Salle de sport',
    descriptionField: 'Description',
    detailedDescription: 'Description Détaillée',
    describeProperty: 'Décrivez votre propriété en détail...',
    contactInformationTitle: 'Informations de Contact',
    fullNameField: 'Nom Complet',
    phoneNumberField: 'Numéro de Téléphone',
    propertyPhotos: 'Photos de la Propriété',
    uploadPhotos: 'Téléchargez vos photos',
    dragDropImages: 'Glissez-déposez vos images ici ou cliquez pour sélectionner (Max 10 images)',
    selectImages: 'Sélectionner des Images',
    publishPropertyBtn: 'Publier la Propriété',
    completed: 'Complété',
    incompleteStep: 'Étape incomplète',
    completeRequiredFields: 'Veuillez compléter tous les champs requis',
    next: 'Suivant',
    previous: 'Précédent',
    
    // Property page translations
    contactOwner: 'Contacter le Propriétaire',
    characteristics: 'Caractéristiques',
    listingDetails: 'Détails de l\'Annonce',
    reference: 'Référence',
    typeField: 'Type',
    publishedOn: 'Publié le',
    lastUpdated: 'Dernière mise à jour',
    daysAgo: 'il y a 2 jours',
    // Cities translations
    exploreByTitle: 'Explorez par',
    citiesTitle: 'Villes',
    citiesDescription: 'Découvrez les meilleures opportunités immobilières dans les principales villes d\'Algérie',
    discoverCity: 'Découvrir',
    allCitiesAvailable: 'Toutes les villes disponibles',
    moreThanCitiesAvailable: 'Plus de 20 villes disponibles',
    showLess: 'Voir moins',
    seeAllCities: 'Voir toutes les villes',
    
    // City descriptions
    algerDescription: 'La capitale dynamique de l\'Algérie',
    oranDescription: 'La perle de l\'Ouest algérien',
    constantineDescription: 'La ville des ponts suspendus',
    annabaDescription: 'La cité du jujubier',
    setifDescription: 'Ville des hautes plaines',
    tlemcenDescription: 'Perle du Maghreb',
    bejaiaDescription: 'Fiancée de la Méditerranée',
    blidaDescription: 'Ville des roses',
  },
  EN: {
    // Navigation
    buy: 'Buy',
    rent: 'Rent',
    shortStay: 'Short Stay',
    about: 'About',
    login: 'Login',
    publishProperty: 'Publish Property',
    
    // Hero
    heroTitle: 'Holibayt',
    heroSubtitle: 'Buy. Rent. Live Algeria differently.',
    heroDescription: 'The first next-generation digital real estate platform for Algeria.',
    
    // Quick Access
    buyProperty: 'Buy a property',
    rentProperty: 'Rent a home',
    shortStayProperty: 'Short stay',
    start: 'Start',
    bookNow: 'Book now',
    
    // Property
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    area: 'Area',
    
    // Common
    search: 'Search',
    cancel: 'Cancel',
    save: 'Save',
    clear: 'Clear',
    from: 'From',
    to: 'To',
    selectDate: 'Select date',
    selectDates: 'Select dates',
    
    // Login
    loginSuccess: 'Login successful!',
    loginSuccessDesc: 'You are now logged in to your Holibayt account.',
    loginDescription: 'Sign in to your Holibayt account',
    email: 'Email address',
    emailPlaceholder: 'your@email.com',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don\'t have an account?',
    createAccount: 'Create account',
    
    // Pages
    propertiesForSale: 'Properties for Sale',
    propertiesForSaleDesc: 'Discover our best properties available for purchase',
    propertiesForRent: 'Properties for Rent',
    propertiesForRentDesc: 'Find your ideal rental',
    shortStayTitle: 'Short Stays',
    shortStayDesc: 'Perfect accommodations for your short stays',
    
    // Quick Access Section
    howCanWeHelp: 'How can we help you?',
    quickEntriesDesc: 'Quick entries for all your real estate needs',
    buyPropertyTitle: 'Buy a property',
    buyPropertyDesc: 'Discover the best opportunities for sale',
    buyPropertySubtitle: 'Investment & main residence',
    rentPropertyTitle: 'Rent a home',
    rentPropertyDesc: 'Find your next home',
    rentPropertySubtitle: 'Long-term rental',
    shortStayTitle2: 'Short stay',
    shortStayDesc2: 'Book your accommodation for a few nights',
    shortStaySubtitle: 'Vacations & business trips',
    needHelp: 'Need help making your choice?',
    speakToAdvisor: 'Speak to an advisor',
    
    // Services Section
    threeWaysToLive: 'Three ways to',
    liveAlgeria: 'live Algeria',
    platformDesc: 'A unique platform for all your real estate needs. Whether you\'re looking to buy, rent or stay, we support you with confidence and transparency.',
    buyTitle: 'Buy',
    buySubtitle: 'Find your future home',
    buyDescription: 'Discover a rigorous selection of verified real estate properties. From city center apartments to seaside villas, find your dream property in Algeria.',
    rentTitle: 'Rent',
    rentSubtitle: 'Long-term rental',
    rentDescription: 'Whether you\'re a student, professional or family, find your ideal rental with security guarantees and trusted landlords.',
    stayTitle: 'Short Stay',
    staySubtitle: 'Short stays and vacations',
    stayDescription: 'The Algerian Airbnb! Book your perfect stay for your vacations, business trips or family visits. Unique accommodations and authentic experiences.',
    explore: 'Explore',
    whyChooseHolibayt: 'Why choose Holibayt?',
    securityGuaranteed: 'Security guaranteed',
    securityDesc: 'All our properties and users are verified',
    premiumQuality: 'Premium quality',
    qualityDesc: 'A rigorous selection for your satisfaction',
    support247: 'Support 24/7',
    supportDesc: 'A team dedicated to your service',
    
    // Hero placeholders and options
    cityNeighborhood: 'City, neighborhood or address',
    whereToRent: 'Where are you looking to rent?',
    stayDestination: 'Your stay destination',
    propertyType: 'Property type',
    apartment: 'Apartment',
    house: 'House',
    villa: 'Villa',
    land: 'Land',
    maxBudget: 'Max budget',
    housingType: 'Housing type',
    studio: 'Studio',
    room: 'Room',
    maxRentMonth: 'Max rent/month',
    stayDates: 'Stay dates',
    stayDuration: 'Stay duration',
    night: 'night',
    nights: 'nights', 
    quickSelection: 'Quick selection',
    oneNight: '1 night',
    oneWeek: '1 week',
    weekend: 'Weekend',
    oneMonth: '1 month',
    checkIn: 'Check-in', 
    checkOut: 'Check-out',
    travelers: 'Travelers',
    availableProperties: 'Available properties',
    satisfiedUsers: 'Satisfied users',
    wilayasCovered: 'Wilayas covered',
    
    // Footer translations
    footerDescription: 'Your trusted real estate platform in Algeria',
    quickLinks: 'Quick Links',
    services: 'Services',
    contact: 'Contact',
    propertyValuation: 'Property valuation',
    legalSupport: 'Legal support',
    mortgageAdvice: 'Mortgage advice',
    allRightsReserved: 'All rights reserved',
    
    // About page translations
    aboutBeitik: 'About Beitik',
    aboutDescription: 'Beitik is Algeria\'s leading real estate platform, connecting buyers, sellers and tenants for over 15 years. Our mission is to simplify your real estate transactions.',
    properties: 'Properties',
    propertiesListed: 'Properties listed',
    clients: 'Clients',
    satisfiedClients: 'Satisfied clients',
    experience: 'Experience',
    years: 'years',
    realEstateExpertise: 'Of real estate expertise',
    security: 'Security',
    secureTransactions: 'Secure transactions',
    ourStory: 'Our Story',
    storyParagraph1: 'Founded in 2009, Beitik revolutionized the Algerian real estate market by creating the first online platform dedicated to real estate in Algeria.',
    storyParagraph2: 'We started with a simple vision: make real estate accessible to everyone and facilitate transactions between individuals and professionals.',
    storyParagraph3: 'Today, we are proud to be the reference platform with more than 10,000 active properties and a community of more than 50,000 users.',
    storyParagraph4: 'Our team of experts works every day to improve your experience and support you in your real estate projects.',
    ourMission: 'Our Mission',
    missionDescription: 'Democratize access to real estate in Algeria by offering a modern, secure and easy-to-use platform.',
    ourVision: 'Our Vision',
    visionDescription: 'Become the essential reference for real estate in the Maghreb and transform the way people buy and rent.',
    ourValues: 'Our Values',
    valuesDescription: 'Transparency, trust, innovation and exceptional customer service are at the heart of everything we do.',
    
    // Publish property translations
    addPropertyDetails: 'Add your property details',
    propertyPublished: 'Property published!',
    propertySubmittedSuccess: 'Your property has been successfully submitted and will be reviewed shortly.',
    
    // Cities and additional translations
    followUs: 'Follow us',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    cookies: 'Cookies',
    
    // Contact advisor translations
    chooseContactMethod: 'Choose Your Preferred Contact Method',
    multipleWaysConnect: 'Multiple ways to connect with our expert advisors',
    phoneSupport: 'Phone Support',
    speakDirectly: 'Speak directly with our advisors',
    emailSupport: 'Email Support',
    getDetailedAssistance: 'Get detailed assistance via email',
    liveChat: 'Live Chat',
    instantMessaging: 'Instant messaging with our team',
    chatNow: 'Chat Now',
    available247: '24/7 Available',
    responseWithin2h: 'Response within 2 hours',
    onlineNow: 'Online now',
    expertAdvisors: 'Expert Advisors',
    averageRating: 'Average Rating',
    averageResponseTime: 'Average Response Time',
    sendMessage: 'Send Message',
    fullName: 'Full Name',
    yourFullName: 'Your full name',
    phoneNumber: 'Phone Number',
    subject: 'Subject',
    whatCanWeHelp: 'What can we help you with?',
    message: 'Message',
    tellUsMore: 'Tell us more about your property needs...',
    ourOffice: 'Our Office',
    businessHours: 'Business Hours',
    mondayFriday: 'Monday - Friday: 8:00 AM - 8:00 PM',
    saturday: 'Saturday: 9:00 AM - 6:00 PM',
    sunday: 'Sunday: 10:00 AM - 4:00 PM',
    needImmediateHelp: 'Need Immediate Help?',
    call247Hotline: 'Call our 24/7 emergency hotline',
    
    // Property and publish property translations
    propertyTypeTranslation: 'Property Type',
    forSale: 'For Sale',
    forRent: 'For Rent', 
    shortStayRent: 'Short Stay',
    basicInformation: 'Basic Information',
    propertyTitleField: 'Property Title',
    propertyTitlePlaceholder: 'Ex: Beautiful villa with garden',
    categoryField: 'Category',
    selectCategory: 'Select category',
    duplex: 'Duplex',
    hotel: 'Hotel',
    guesthouse: 'Guesthouse',
    locationField: 'Location',
    cityField: 'City',
    district: 'District/Area',
    fullAddress: 'Full Address',
    propertyDetailsTitle: 'Property Details',
    chambers: 'Bedrooms',
    numberField: 'Number',
    areaField: 'Area (m²)',
    floorField: 'Floor',
    floorExample: 'Ex: 2nd',
    pricing: 'Pricing',
    priceDZD: 'Price (DZD)',
    priceExample: 'Ex: 2,500,000',
    priceTypeField: 'Price Type',
    totalPrice: 'Total price',
    monthlyPrice: 'Per month',
    dailyPrice: 'Per day',
    weeklyPrice: 'Per week',
    featuresAmenities: 'Features & Amenities',
    parkingFeature: 'Parking',
    swimmingPoolFeature: 'Swimming Pool',
    gardenFeature: 'Garden',
    balconyFeature: 'Balcony',
    elevatorFeature: 'Elevator',
    securityFeature: 'Security',
    furnishedFeature: 'Furnished',
    airConditioningFeature: 'Air Conditioning',
    gymFeature: 'Gym',
    descriptionField: 'Description',
    detailedDescription: 'Detailed Description',
    describeProperty: 'Describe your property in detail...',
    contactInformationTitle: 'Contact Information',
    fullNameField: 'Full Name',
    phoneNumberField: 'Phone Number',
    propertyPhotos: 'Property Photos',
    uploadPhotos: 'Upload your photos',
    dragDropImages: 'Drag and drop your images here or click to select (Max 10 images)',
    selectImages: 'Select Images',
    publishPropertyBtn: 'Publish Property',
    completed: 'Completed',
    incompleteStep: 'Incomplete step',
    completeRequiredFields: 'Please complete all required fields',
    next: 'Next',
    previous: 'Previous',
    
    // Property page translations
    contactOwner: 'Contact Owner',
    characteristics: 'Characteristics',
    listingDetails: 'Listing Details',
    reference: 'Reference',
    typeField: 'Type',
    publishedOn: 'Published on',
    lastUpdated: 'Last updated',
    daysAgo: '2 days ago',
    // Cities translations
    exploreByTitle: 'Explore by',
    citiesTitle: 'Cities',
    citiesDescription: 'Discover the best real estate opportunities in Algeria\'s main cities',
    discoverCity: 'Discover',
    allCitiesAvailable: 'All available cities',
    moreThanCitiesAvailable: 'More than 20 cities available',
    showLess: 'Show Less',
    seeAllCities: 'See All Cities',
    
    // City descriptions
    algerDescription: 'Algeria\'s dynamic capital',
    oranDescription: 'Pearl of Western Algeria',
    constantineDescription: 'City of suspended bridges',
    annabaDescription: 'City of the jujube tree',
    setifDescription: 'City of the High Plains',
    tlemcenDescription: 'Pearl of the Maghreb',
    bejaiaDescription: 'Bride of the Mediterranean',
    blidaDescription: 'City of Roses',
  },
  AR: {
    // Navigation
    buy: 'شراء',
    rent: 'إيجار',
    shortStay: 'إقامة قصيرة',
    about: 'حول',
    login: 'تسجيل الدخول',
    publishProperty: 'نشر عقار',
    
    // Hero
    heroTitle: 'هولي بايت',
    heroSubtitle: 'اشتري. استأجر. عش الجزائر بشكل مختلف.',
    heroDescription: 'أول منصة عقارية رقمية من الجيل الجديد للجزائر.',
    
    // Quick Access
    buyProperty: 'شراء عقار',
    rentProperty: 'استئجار منزل',
    shortStayProperty: 'إقامة قصيرة',
    start: 'ابدأ',
    bookNow: 'احجز الآن',
    
    // Property
    bedrooms: 'غرف النوم',
    bathrooms: 'دورات المياه',
    area: 'المساحة',
    
    // Common
    search: 'بحث',
    cancel: 'إلغاء',
    save: 'حفظ',
    clear: 'مسح',
    from: 'من',
    to: 'إلى',
    selectDate: 'اختر التاريخ',
    selectDates: 'اختر التواريخ',
    
    // Login
    loginSuccess: 'تم تسجيل الدخول بنجاح!',
    loginSuccessDesc: 'أنت الآن متصل بحساب هولي بايت الخاص بك.',
    loginDescription: 'سجل الدخول إلى حساب هولي بايت',
    email: 'عنوان البريد الإلكتروني',
    emailPlaceholder: 'بريدك@الالكتروني.com',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    createAccount: 'إنشاء حساب',
    
    // Pages
    propertiesForSale: 'عقارات للبيع',
    propertiesForSaleDesc: 'اكتشف أفضل العقارات المتاحة للشراء',
    propertiesForRent: 'عقارات للإيجار',
    propertiesForRentDesc: 'اعثر على الإيجار المثالي',
    shortStayTitle: 'الإقامات القصيرة',
    shortStayDesc: 'أماكن إقامة مثالية لإقاماتك القصيرة',
    
    // Quick Access Section
    howCanWeHelp: 'كيف يمكننا مساعدتك؟',
    quickEntriesDesc: 'مداخل سريعة لجميع احتياجاتك العقارية',
    buyPropertyTitle: 'شراء عقار',
    buyPropertyDesc: 'اكتشف أفضل الفرص للبيع',
    buyPropertySubtitle: 'استثمار ومسكن رئيسي',
    rentPropertyTitle: 'استئجار منزل',
    rentPropertyDesc: 'اعثر على منزلك القادم',
    rentPropertySubtitle: 'إيجار طويل المدى',
    shortStayTitle2: 'إقامة قصيرة',
    shortStayDesc2: 'احجز إقامتك لبضع ليال',
    shortStaySubtitle: 'إجازات ورحلات عمل',
    needHelp: 'تحتاج مساعدة في اتخاذ القرار؟',
    speakToAdvisor: 'تحدث إلى مستشار',
    
    // Services Section
    threeWaysToLive: 'ثلاث طرق لـ',
    liveAlgeria: 'عيش الجزائر',
    platformDesc: 'منصة فريدة لجميع احتياجاتك العقارية. سواء كنت تبحث عن الشراء أو الإيجار أو الإقامة، نحن ندعمك بثقة وشفافية.',
    buyTitle: 'شراء',
    buySubtitle: 'اعثر على منزل المستقبل',
    buyDescription: 'اكتشف مجموعة مختارة بعناية من العقارات المتحققة. من الشقق في وسط المدينة إلى الفيلات على شاطئ البحر، اعثر على العقار الذي تحلم به في الجزائر.',
    rentTitle: 'إيجار',
    rentSubtitle: 'إيجار طويل المدى',
    rentDescription: 'سواء كنت طالبًا أو محترفًا أو عائلة، اعثر على الإيجار المثالي مع ضمانات الأمان وملاك موثوقين.',
    stayTitle: 'إقامة قصيرة',
    staySubtitle: 'إقامات قصيرة وإجازات',
    stayDescription: 'Airbnb الجزائري! احجز إقامتك المثالية لإجازاتك أو رحلات العمل أو الزيارات العائلية. أماكن إقامة فريدة وتجارب أصيلة.',
    explore: 'استكشف',
    whyChooseHolibayt: 'لماذا تختار هولي بايت؟',
    securityGuaranteed: 'الأمان مضمون',
    securityDesc: 'جميع عقاراتنا ومستخدمينا متحققون',
    premiumQuality: 'جودة ممتازة',
    qualityDesc: 'اختيار دقيق لرضاك',
    support247: 'دعم 24/7',
    supportDesc: 'فريق مخصص لخدمتك',
    
    // Hero placeholders and options
    cityNeighborhood: 'المدينة، الحي أو العنوان',
    whereToRent: 'أين تبحث عن الإيجار؟',
    stayDestination: 'وجهة إقامتك',
    propertyType: 'نوع العقار',
    apartment: 'شقة',
    house: 'منزل',
    villa: 'فيلا',
    land: 'أرض',
    maxBudget: 'الحد الأقصى للميزانية',
    housingType: 'نوع السكن',
    studio: 'استوديو',
    room: 'غرفة',
    maxRentMonth: 'أقصى إيجار/شهر',
    stayDates: 'تواريخ الإقامة',
    stayDuration: 'مدة الإقامة',
    night: 'ليلة',
    nights: 'ليال',
    quickSelection: 'اختيار سريع',
    oneNight: 'ليلة واحدة',
    oneWeek: 'أسبوع واحد',
    weekend: 'عطلة نهاية الأسبوع',
    oneMonth: 'شهر واحد',
    checkIn: 'تسجيل الوصول',
    checkOut: 'تسجيل المغادرة',
    travelers: 'المسافرون',
    availableProperties: 'العقارات المتاحة',
    satisfiedUsers: 'المستخدمون الراضون',
    wilayasCovered: 'الولايات المغطاة',
    
    // Footer translations
    footerDescription: 'منصتك العقارية الموثوقة في الجزائر',
    quickLinks: 'روابط سريعة',
    services: 'الخدمات',
    contact: 'اتصل بنا',
    propertyValuation: 'تقييم العقارات',
    legalSupport: 'الدعم القانوني',
    mortgageAdvice: 'نصائح الرهن العقاري',
    allRightsReserved: 'جميع الحقوق محفوظة',
    
    // About page translations
    aboutBeitik: 'حول بيتك',
    aboutDescription: 'بيتك هي منصة العقارات الرائدة في الجزائر، تربط المشترين والبائعين والمستأجرين لأكثر من 15 عامًا. مهمتنا هي تبسيط معاملاتك العقارية.',
    properties: 'العقارات',
    propertiesListed: 'العقارات المدرجة',
    clients: 'العملاء',
    satisfiedClients: 'العملاء الراضون',
    experience: 'الخبرة',
    years: 'سنة',
    realEstateExpertise: 'من الخبرة العقارية',
    security: 'الأمان',
    secureTransactions: 'معاملات آمنة',
    ourStory: 'قصتنا',
    storyParagraph1: 'تأسست بيتك في عام 2009، وثورت السوق العقاري الجزائري من خلال إنشاء أول منصة عبر الإنترنت مخصصة للعقارات في الجزائر.',
    storyParagraph2: 'بدأنا برؤية بسيطة: جعل العقارات في متناول الجميع وتسهيل المعاملات بين الأفراد والمهنيين.',
    storyParagraph3: 'اليوم، نحن فخورون بكوننا المنصة المرجعية مع أكثر من 10,000 عقار نشط ومجتمع من أكثر من 50,000 مستخدم.',
    storyParagraph4: 'يعمل فريق خبرائنا كل يوم لتحسين تجربتك ودعمك في مشاريعك العقارية.',
    ourMission: 'مهمتنا',
    missionDescription: 'إضفاء الطابع الديمقراطي على الوصول إلى العقارات في الجزائر من خلال تقديم منصة حديثة وآمنة وسهلة الاستخدام.',
    ourVision: 'رؤيتنا',
    visionDescription: 'أن نصبح المرجع الأساسي للعقارات في المغرب العربي وتحويل الطريقة التي يشتري ويستأجر بها الناس.',
    ourValues: 'قيمنا',
    valuesDescription: 'الشفافية والثقة والابتكار وخدمة العملاء الاستثنائية هي في قلب كل ما نقوم به.',
    
    // Publish property translations
    addPropertyDetails: 'أضف تفاصيل عقارك',
    propertyPublished: 'تم نشر العقار!',
    propertySubmittedSuccess: 'تم إرسال عقارك بنجاح وسيتم مراجعته قريبًا.',
    
    // Cities and additional translations
    followUs: 'تابعنا',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    cookies: 'ملفات تعريف الارتباط',
    
    // Contact advisor translations
    chooseContactMethod: 'اختر طريقة الاتصال المفضلة لديك',
    multipleWaysConnect: 'طرق متعددة للتواصل مع مستشارينا الخبراء',
    phoneSupport: 'الدعم الهاتفي',
    speakDirectly: 'تحدث مباشرة مع مستشارينا',
    emailSupport: 'الدعم عبر البريد الإلكتروني',
    getDetailedAssistance: 'احصل على مساعدة مفصلة عبر البريد الإلكتروني',
    liveChat: 'الدردشة المباشرة',
    instantMessaging: 'مراسلة فورية مع فريقنا',
    chatNow: 'ادردش الآن',
    available247: 'متاح 24/7',
    responseWithin2h: 'الرد خلال ساعتين',
    onlineNow: 'متصل الآن',
    expertAdvisors: 'مستشارون خبراء',
    averageRating: 'التقييم المتوسط',
    averageResponseTime: 'متوسط وقت الاستجابة',
    sendMessage: 'أرسل رسالة',
    fullName: 'الاسم الكامل',
    yourFullName: 'اسمك الكامل',
    phoneNumber: 'رقم الهاتف',
    subject: 'الموضوع',
    whatCanWeHelp: 'كيف يمكننا مساعدتك؟',
    message: 'الرسالة',
    tellUsMore: 'أخبرنا المزيد عن احتياجاتك العقارية...',
    ourOffice: 'مكتبنا',
    businessHours: 'ساعات العمل',
    mondayFriday: 'الاثنين - الجمعة: 8:00 صباحًا - 8:00 مساءً',
    saturday: 'السبت: 9:00 صباحًا - 6:00 مساءً',
    sunday: 'الأحد: 10:00 صباحًا - 4:00 مساءً',
    needImmediateHelp: 'تحتاج مساعدة فورية؟',
    call247Hotline: 'اتصل بخط الطوارئ الخاص بنا على مدار الساعة',
    
    // Property and publish property translations  
    propertyTypeTranslation: 'نوع العقار',
    forSale: 'للبيع',
    forRent: 'للإيجار',
    shortStayRent: 'إقامة قصيرة',
    basicInformation: 'المعلومات الأساسية',
    propertyTitleField: 'عنوان العقار',
    propertyTitlePlaceholder: 'مثال: فيلا جميلة مع حديقة',
    categoryField: 'الفئة',
    selectCategory: 'اختر الفئة',
    duplex: 'دوبلكس',
    hotel: 'فندق',
    guesthouse: 'بيت ضيافة',
    locationField: 'الموقع',
    cityField: 'المدينة',
    district: 'المنطقة/الحي',
    fullAddress: 'العنوان الكامل',
    propertyDetailsTitle: 'تفاصيل العقار',
    chambers: 'غرف النوم',
    numberField: 'العدد',
    areaField: 'المساحة (م²)',
    floorField: 'الطابق',
    floorExample: 'مثال: الثاني',
    pricing: 'التسعير',
    priceDZD: 'السعر (دج)',
    priceExample: 'مثال: 2,500,000',
    priceTypeField: 'نوع السعر',
    totalPrice: 'السعر الإجمالي',
    monthlyPrice: 'شهريًا',
    dailyPrice: 'يوميًا',
    weeklyPrice: 'أسبوعيًا',
    featuresAmenities: 'الميزات والتجهيزات',
    parkingFeature: 'موقف سيارات',
    swimmingPoolFeature: 'مسبح',
    gardenFeature: 'حديقة',
    balconyFeature: 'شرفة',
    elevatorFeature: 'مصعد',
    securityFeature: 'أمان',
    furnishedFeature: 'مفروش',
    airConditioningFeature: 'تكييف',
    gymFeature: 'صالة رياضية',
    descriptionField: 'الوصف',
    detailedDescription: 'وصف مفصل',
    describeProperty: 'صف عقارك بالتفصيل...',
    contactInformationTitle: 'معلومات الاتصال',
    fullNameField: 'الاسم الكامل',
    phoneNumberField: 'رقم الهاتف',
    propertyPhotos: 'صور العقار',
    uploadPhotos: 'ارفع صورك',
    dragDropImages: 'اسحب وأفلت صورك هنا أو انقر للاختيار (حد أقصى 10 صور)',
    selectImages: 'اختر الصور',
    publishPropertyBtn: 'نشر العقار',
    completed: 'مكتمل',
    incompleteStep: 'خطوة غير مكتملة',
    completeRequiredFields: 'يرجى إكمال جميع الحقول المطلوبة',
    next: 'التالي',
    previous: 'السابق',
    
    // Property page translations
    contactOwner: 'الاتصال بالمالك',
    characteristics: 'الخصائص',
    listingDetails: 'تفاصيل الإعلان',
    reference: 'المرجع',
    typeField: 'النوع',
    publishedOn: 'نُشر في',
    lastUpdated: 'آخر تحديث',
    daysAgo: 'منذ يومين',
    
    // Cities translations
    exploreByTitle: 'استكشف حسب',
    citiesTitle: 'المدن',
    citiesDescription: 'اكتشف أفضل الفرص العقارية في المدن الرئيسية بالجزائر',
    discoverCity: 'اكتشف',
    allCitiesAvailable: 'جميع المدن المتاحة',
    moreThanCitiesAvailable: 'أكثر من 20 مدينة متاحة',
    showLess: 'إظهار أقل',
    seeAllCities: 'رؤية جميع المدن',
    
    // City descriptions  
    algerDescription: 'العاصمة النشطة للجزائر',
    oranDescription: 'لؤلؤة الغرب الجزائري',
    constantineDescription: 'مدينة الجسور المعلقة',
    annabaDescription: 'مدينة النبق',
    setifDescription: 'مدينة الهضاب العليا',
    tlemcenDescription: 'لؤلؤة المغرب الأوسط',
    bejaiaDescription: 'عروس البحر الأبيض المتوسط',
    blidaDescription: 'مدينة الورود',
    
    callBtn: 'اتصال',
    sendMessageBtn: 'أرسل رسالة'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLang, setCurrentLang] = useState<Language>('FR');

  const t = (key: string): string => {
    return translations[currentLang][key as keyof typeof translations['FR']] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};