// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xazqwzusexxkecsjanzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhenF3enVzZXh4a2Vjc2phbnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDQyNjQsImV4cCI6MjA3MzA4MDI2NH0.CjpVNAnJ3a5ek1QY1Y3UFaSCA9uUPEmcOUbRI-bzoms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});